### ISSUE TITLE
AttributeError: module 'adminactions.compat' has no attribute 'nocommit'

### ISSUE THREAD

**Issue by martinzellner** [saxix/django-adminactions#109]
Hello,

I'm unable to get the merge to work. I am using Django 1.9 and django-reversions.

Any ideas?

Best,
Martin
```
 Traceback (most recent call last):
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
django_1  |     response = self.process_exception_by_middleware(e, request)
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
django_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py", line 541, in wrapper
django_1  |     return self.admin_site.admin_view(view)(*args, **kwargs)
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
django_1  |     response = view_func(request, *args, **kwargs)
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
django_1  |     response = view_func(request, *args, **kwargs)
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 244, in inner
django_1  |     return view(request, *args, **kwargs)
django_1  |   File "/usr/local/lib/python3.5/site-packages/reversion/admin.py", line 247, in changelist_view
django_1  |     return super(VersionAdmin, self).changelist_view(request, context)
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
django_1  |     return bound_func(*args, **kwargs)
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
django_1  |     response = view_func(request, *args, **kwargs)
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
django_1  |     return func.__get__(self, type(self))(*args2, **kwargs2)
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1512, in changelist_view
django_1  |     response = self.response_action(request, queryset=cl.get_queryset(request))
django_1  |   File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1245, in response_action
django_1  |     response = func(self, request, queryset)
django_1  |   File "/code/adminactions/merge.py", line 112, in merge
django_1  |     with transaction.nocommit():
django_1  | AttributeError: module 'adminactions.compat' has no attribute 'nocommit'
```

**Comment by saxix** [comment]
what version are you using ?

2017-01-12 16:39 GMT+01:00 Martin Zellner <notifications@github.com>:

**Comment by martinzellner** [comment]
I am using:
```
Django (1.9.12)
django-adminactions (1.1)
django-reversion (2.0.8)
```

I also tried django-adminactions 1.2 but the same problem persits.
